export const CONSTANTS = {
    MULTIPLICADOR_IMPUESTO_PAIS: 0.30,
    MULTIPLICADOR_IMPUESTO_GANANCIAS: 0.35,
    ARGENTINA_COUNTRY_CODE: 'AR',
    USA_COUNTRY_CODE: 'US',
    VALOR_OFICIAL_KEY: 'ar_oficial_sell',
    VALOR_BLUE_KEY: 'ar_blue_sell'
}